services:
    web:
        container_name: web
        build:
            dockerfile: Dockerfile.dev
            context: .
        develop:
            watch:
                - action: sync
                  path: .
                  target: /app
        ports:
            - 5173:5173
        env_file:
            - .env
        command: npm run dev
        # volumes:
        #     - .:/app/web
