FROM node:23-slim

# set working directory
WORKDIR /app/web

# copies local files to the docker container
COPY . . 

# work around npm optional dependencies bug
RUN rm -rf package-lock.json

RUN npm install --include=optional

EXPOSE 5173